spring.application.name=demo


spring.datasource.url=jdbc:mysql://localhost:3306/bd_nanas
spring.datasource.username=root
spring.datasource.password=061105
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Desactivar temporalmente el bloqueo de Spring Security para desarrollo
spring.security.user.password=admin
